/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : debug_console.h
**     Project     : Atlas_Main_MCU_REVA
**     Processor   : MK22FN512VDC12
**     Component   : fsl_debug_console
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-14, 13:36, # CodeGen: 1
**     Abstract    :
**
**     Contents    :
**         DbgConsole_Init   - debug_console_status_t DbgConsole_Init(uint32_t uartInstance,uint32_t...
**         DbgConsole_DeInit - debug_console_status_t DbgConsole_DeInit(void);
**         debug_printf      - int debug_printf(const char * fmt_s,...);
**         debug_putchar     - int debug_putchar(int ch);
**         debug_scanf       - int debug_scanf(const char * fmt_ptr,...);
**         debug_getchar     - int debug_getchar(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file debug_console.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup debug_console_module debug_console module documentation
**  @{
*/         
#ifndef __debug_console_H
#define __debug_console_H
/* MODULE debug_console. */
/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"
#include "fsl_debug_console.h"
  
/** Device instance number */
#define BOARD_DEBUG_UART_INSTANCE UART0_IDX
/** Baud rate in bits per second. */
#define DEBUG_UART_BAUD 256000U
/** Low level device type */
#define DEBUG_UART_TYPE kDebugConsoleUART
 
#endif
/* ifndef __debug_console_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
